config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'settings/unsubscribe'
    patch 'settings/update'
  end

  root to: 'blog_posts#index'
  devise_for :users , :controllers => { :omniauth_callbacks => "omniauth_callbacks" , :invitations => "invitations" }, :skip => [:registration]
  devise_scope :user do
    # using login path for registration
    get '/users/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    get '/users/edit' => 'registrations#edit', :as => :edit_user_registration
    put '/users' => 'registrations#update' 
    patch '/users' => 'registrations#update' 
    delete '/users' => 'registrations#destroy'
  end
  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
  resources :images
  resources :post_categories, :path => 'categories',  only:[:index, :show]
  resources :user_notification_preferences , :path => 'user/preferences' do
      collection do 
        get 'unsubscribe'
        patch 'update'

      end
  end
  # resources :users do
  #   collection do
  #     post :follow, :to => "users#follow", :as => 'users/follow'
  #     patch :unfollow, :to => "users#unfollow", :as => 'users/unfollow'
  #   end
  # end
  as :user do
    post :validate_useremail , :to => "users#validate_useremail", :as => 'validate_useremail'
  end

  # Routes for admin dashboard starts here
  namespace :admin, :path => "/dashboard" do
    get 'companies/posts',:to => "blog_posts#index"
    post 'companies/posts',:to => "blog_posts#index"
    post :unfollow_company, :to => "users#unfollow_company" , :as => '/unfollow_company'
    post :unfollow_user , :to => "users#unfollow_user" , :as => '/unfollow_user'
    post :remove_bookmark, :to => "users#remove_bookmark", :as => '/remove_bookmark'
    post "validate_blog_post_slug" => "blog_posts#validate_blog_post_slug"
    # post '/user' , :to => "users#index"
    get "/remove_featured_image/:id" => "blog_posts#remove_featured_image"
    resources :user_notification_preferences , :path => 'user/preferences' do 
      collection do 
        get 'edit_multiple'
        patch 'update'

      end
    end
    resources :users do
      post 'admin/users' , :to => "blog_post#index"
      collection do
        get :followed_companies, :to => "users#followed_companies", :as => '/folllowed_companies'
        get :bookmarked_companies, :to => "users#bookmarked_companies", :as => '/bookmarked_companies'
        get :followed_users, :to => "users#followed_users", :as => '/followed_users'
        get :newsletter_enable_status, :to => "users#newsletter_enable_status", :as => "/newsletter_enable_status"
        patch :update_newsletter_status, :to => "users#update_newsletter_status"
      end
    end
    resources :newsletters
        get '/newsletter/unsubscribe', :to => "newsletters#unsubscribe" , :as => "unsubscribe"
        # post :unsubscribe, :to => "newsletters#unsubscribe"
    resources :roles do
      collection do
        get "role" => "roles#show_roles"
        post 'roles/assign'
      end
    end
    resources :admin, :path => '', only:[:index]
      resources :companies, :path => "companies" ,except:[:show] do
      
        collection do
          post :validate_user, :to => "companies#validate_user", :as => 'validate_user'
        end
        resources :albums
        resources :testimonials
        resources :blog_posts, :path => '/posts', except:[:show]  do
          collection do
            post "upload_post_image" => "blog_posts#upload_post_image"
            get 'drafts'   => "blog_posts#draft_posts"
            get 'tag/:tag_name' => "blog_posts#show_tags_blog_posts", :as => "tag"
            get 'category/:category_name' => "blog_posts#show_category_blog_posts", :as => "category"
          end
      end
    end
    resources :images
    resources :post_categories , :path => '/post/categories',  except:[:show]
  end
  # Routes for admget 'users', :to => 'users#index' , :as => 'users'in dashboard ends here
  
  # routes for Companies, omitting path (controller name)
  resources :companies , :path => "" ,only:[:show,:index] do
    collection do
      post :validate_slug , :to => "companies#validate_slug", :as => 'validate_slug'
      post "/companies/subscribe", :to => "companies#subscribe", :as => 'subscribe'
      patch "/companies/unsubscribe", :to => "companies#unsubscribe", :as => 'unsubscribe'
      post "/companies/bookmark", :to => "companies#bookmark", :as => 'bookmark'
      post :validate_user, :to => "companies#validate_user", :as => 'validate_user'
      patch "/companies/bookmarked", :to => "companies#bookmarked", :as => 'bookmarked'
      get :view, :to => "companies#view_companies", :as => 'view'
      get "view/:category-in-:location", :to => "companies#view_companies" , :as => 'company_location'
      post "/companies" => "companies#create"
      get "/companies" => "companies#index"
      post "/companies" => "companies#index"
      get 'posts',:to => "blog_posts#index"
      post 'posts', :to => "blog_posts#index"
      get 'unpublished_posts',to: "blog_posts#unpublished_posts"
      get 'visible_to_followers_posts', to: "blog_posts#visible_to_followers_posts"
      get 'all-posts', to: "blog_posts#all_posts"
      get 'trending-featured-posts', to: 'blog_posts#trending_posts'
      # get "/remove_featured_image/:id" => "blog_posts#remove_featured_image"
    end
      get 'users', :to => 'users#index' , :as => 'users'
      post 'users', :to => 'users#index' 
    resources :users , :path => "" , only:[:show] do
      collection do
        # get ':id',  controller: "users", action: "show" , :as => "user"
        post :follow, :to => "users#follow", :as => 'users/follow'
        patch :unfollow, :to => "users#unfollow", :as => 'users/unfollow'
      end
    end
    # Nested collection route for companies
    resources :albums, only:[:show]

    resources :testimonials, only:[:show]
  end
  resources :blog_posts, :path => '', only:[:index]  do
    collection do
      get ':company_id/tag/:tag_name',to: "blog_posts#show_tags_blog_posts", :as => "tag_name"
      get ':company_id/category/:category_name', to: "blog_posts#show_category_blog_posts", :as => "category_name"
      get ':company_id/:user_id/:id',  controller: "blog_posts", action: "show" , :as => "blog_post"
    end  
  end
end

app/views/layouts/dashboard/_content.html.erb
<!-- Content Wrapper. Contains page content -->
  <section class="content-header">
   <!--  <ol class="breadcrumb">
      <li><a href="/dashboard"><i class="fa fa-dashboard"></i>Dashboard</a></li>
      <li class="active">Here</li>
    </ol> -->
  </section>
  <section class="content container-fluid">
    <div class="notice-class">
      <%#if params[:controller] == "admin/users" && params[:action] == "edit" %>
          <%#if notice.present?%>
           
          <%#end%>
      <%#else%>
        <%if notice.present?%>
            <div class="alert alert-success">
              <p id="notice"><%= notice %></p>
            </div>
          <%end%>
      <%#end%>
    </div>
    <%= yield %>
  </section>
<div id="img-loader">
	 <%#= image_tag "load-icon.png", :id => "load-image" %>
</div>	

app/views/layouts/dashboard/_footer.html.erb
<!-- Main Footer -->
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2017 <a href="http://www.uimatic.com/" , target='_blank' >Uimatic</a>.</strong> All rights reserved.

app/views/layouts/dashboard/_header.html.erb
<!-- Main Header -->
  <!-- Logo -->
  <a href="/dashboard" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>U</b>ims</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Stairs</b></span>
  </a>
<!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <%if user_signed_in? && current_user.avatar.present? %>
              <%= image_tag(current_user.avatar.url ,size: "20x20")%>
            <%elsif user_signed_in? && !current_user.avatar.present? %>
              <%= image_tag "Default.png"  ,size: "20x20" %>
            <%end%>

            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">
              <%if user_signed_in? %>
                <%= current_user.username%>
              <%end%>
            </span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <%if user_signed_in? && current_user.avatar.present? %>
                <%= image_tag(current_user.avatar.url ,size: "20x20")%>
              <%elsif user_signed_in? && !current_user.avatar.present? %>
                <%= image_tag "Default.png"  ,size: "20x20" %>
              <%end%> 
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="<%= edit_admin_user_path(current_user) %>" class="btn btn-primary">Edit Profile</a>
              </div>
              <div class="pull-right">
                <a href="<%= destroy_user_session_path %>" data-method='delete' class="btn btn-primary" >Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/dashboard/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">Navigation</li>
      <!-- Optionally, you can add icons to the links -->
      <li id="manageCompanies">
       <% if (is_super_admin? || is_admin?) %>
        <a href="<%= admin_companies_path %>">
          <i class="fa fa-building"></i>
          <span>Companies</span>
        </a>
        <%end%>
      </li>
      <li id="managePosts">
      <% if (is_super_admin?)%>
        <a href="<%= admin_companies_posts_path %>" >
          <i class="fa fa-newspaper-o"></i>
          <span>Posts</span>
        </a>
      <%end%>
      <% if (is_manager?)%>
        <%if current_user.company.present? %>
          <a href="<%= admin_company_blog_posts_path(:company_id => current_user.company.slug ) %>" >
            <i class="fa fa-newspaper-o"></i>
            <span>Posts</span>
          </a>
        <%else%>
          <a href="<%= admin_companies_posts_path %>" >
            <i class="fa fa-newspaper-o"></i>
            <span>Posts</span>
          </a>
        <%end%>
      <%elsif is_user? %>
        <%if current_user.company.present? %>
          <a href="<%= admin_company_blog_posts_path(:company_id => current_user.company.slug ) %>" >
            <i class="fa fa-newspaper-o"></i>
            <span>Posts</span>
          </a>
        <%else%>
          <a href="<%= admin_companies_posts_path %>" >
            <i class="fa fa-newspaper-o"></i>
            <span>Posts</span>
          </a>
        <%end%>
      <%elsif is_admin? %>
        <%if current_user.company.present? %>
          <a href="<%= admin_company_blog_posts_path(:company_id => current_user.company.slug ) %>" >
            <i class="fa fa-newspaper-o"></i>
            <span>Posts</span>
          </a>
        <%else%>
          <a href="<%= admin_companies_posts_path %>" >
            <i class="fa fa-newspaper-o"></i>
            <span>Posts</span>
          </a>
        <%end%>
      <%end%>
    </li>

      <li id="manageCategories">
        <a href="<%= admin_post_categories_path %>" >
          <i class="fa fa-certificate"></i>
          <span>Post Categories</span>
        </a>
      </li>
      <% if (!is_super_admin?) %>
      <li id="">
        <a href="<%= folllowed_companies_admin_users_path %>" >
          <i class="fa fa-building"></i>
          <span>Followed Companies</span>
        </a>
      </li>
      <li id="">
        <a href="<%= bookmarked_companies_admin_users_path %>" >
          <i class="fa fa-bookmark"></i>
          <span>Bookmarked Companies</span>
        </a>
      </li>
      <li id="">
        <a href="<%= followed_users_admin_users_path %>" >
          <i class="fa fa-user-plus"></i>
          <span>Followed Users</span>
        </a>
      </li>
      <%end%>
      <% if !is_super_admin? %>
        <li><a href="<%= edit_multiple_admin_user_notification_preferences_path %>" >
                <i class="fa fa-circle-o"></i>Edit User Preferences
            </a>
        </li>
      <%end%>      
      <li id="manageUsers">
      <% if (is_super_admin? || is_admin?) %>
        <a href="<%= admin_users_path %>" >
          <i class="fa fa-users"></i>
          <span>Users</span>
        </a>
      <%end%>
      </li>
      <li class="treeview">
      <% if is_super_admin? %>
          <a href="<%= "#" %>">
          <i class="fa fa-pie-chart"></i>
          <span>Control Panel</span>
          </a>
          <ul class="treeview-menu">
              <li><a href="<%= role_admin_roles_path %>" >
                <i class="fa fa-circle-o"></i>Roles
              </a>
              </li>
              <li><a href="<%= admin_roles_path %>" >
                <i class="fa fa-circle-o"></i>Assign Role Area
              </a>
              </li>
              
            </ul>
      <%end%>
      </li>

     <!--  <li class="active">
        <a href="<%#= admin_company_testimonials_path(@company) %>">
          <i class="fa fa-object-ungroup"></i>
          <span>Testimonials</span>
        </a>
      </li> -->
      <!-- <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#">Link in level 2</a></li>
          <li><a href="#">Link in level 2</a></li>
        </ul>
      </li> -->
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->