config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'settings/unsubscribe'
    patch 'settings/update'
  end

  root to: 'blog_posts#index'
  devise_for :users , :controllers => { :omniauth_callbacks => "omniauth_callbacks" , :invitations => "invitations" }, :skip => [:registration]
  devise_scope :user do
    # using login path for registration
    get '/users/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    get '/users/edit' => 'registrations#edit', :as => :edit_user_registration
    put '/users' => 'registrations#update' 
    patch '/users' => 'registrations#update' 
    delete '/users' => 'registrations#destroy'
  end
  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
  resources :images
  resources :post_categories, :path => 'categories',  only:[:index, :show]
  resources :user_notification_preferences , :path => 'user/preferences' do
      collection do 
        get 'unsubscribe'
        patch 'update'

      end
  end
  # resources :users do
  #   collection do
  #     post :follow, :to => "users#follow", :as => 'users/follow'
  #     patch :unfollow, :to => "users#unfollow", :as => 'users/unfollow'
  #   end
  # end
  as :user do
    post :validate_useremail , :to => "users#validate_useremail", :as => 'validate_useremail'
  end

  # Routes for admin dashboard starts here
  namespace :admin, :path => "/dashboard" do
    get 'companies/posts',:to => "blog_posts#index"
    post 'companies/posts',:to => "blog_posts#index"
    post :unfollow_company, :to => "users#unfollow_company" , :as => '/unfollow_company'
    post :unfollow_user , :to => "users#unfollow_user" , :as => '/unfollow_user'
    post :remove_bookmark, :to => "users#remove_bookmark", :as => '/remove_bookmark'
    post "validate_blog_post_slug" => "blog_posts#validate_blog_post_slug"
    # post '/user' , :to => "users#index"
    get "/remove_featured_image/:id" => "blog_posts#remove_featured_image"
    resources :user_notification_preferences , :path => 'user/preferences' do 
      collection do 
        get 'edit_multiple'
        patch 'update'

      end
    end
    resources :users do
      post 'admin/users' , :to => "blog_post#index"
      collection do
        get :followed_companies, :to => "users#followed_companies", :as => '/folllowed_companies'
        get :bookmarked_companies, :to => "users#bookmarked_companies", :as => '/bookmarked_companies'
        get :followed_users, :to => "users#followed_users", :as => '/followed_users'
        get :newsletter_enable_status, :to => "users#newsletter_enable_status", :as => "/newsletter_enable_status"
        patch :update_newsletter_status, :to => "users#update_newsletter_status"
      end
    end
    resources :newsletters
        get '/newsletter/unsubscribe', :to => "newsletters#unsubscribe" , :as => "unsubscribe"
        # post :unsubscribe, :to => "newsletters#unsubscribe"
    resources :roles do
      collection do
        get "role" => "roles#show_roles"
        post 'roles/assign'
      end
    end
    resources :admin, :path => '', only:[:index]
      resources :companies, :path => "companies" ,except:[:show] do
      
        collection do
          post :validate_user, :to => "companies#validate_user", :as => 'validate_user'
        end
        resources :albums
        resources :testimonials
        resources :blog_posts, :path => '/posts', except:[:show]  do
          collection do
            post "upload_post_image" => "blog_posts#upload_post_image"
            get 'drafts'   => "blog_posts#draft_posts"
            get 'tag/:tag_name' => "blog_posts#show_tags_blog_posts", :as => "tag"
            get 'category/:category_name' => "blog_posts#show_category_blog_posts", :as => "category"
          end
      end
    end
    resources :images
    resources :post_categories , :path => '/post/categories',  except:[:show]
  end
  # Routes for admget 'users', :to => 'users#index' , :as => 'users'in dashboard ends here
  
  # routes for Companies, omitting path (controller name)
  resources :companies , :path => "" ,only:[:show,:index] do
    collection do
      post :validate_slug , :to => "companies#validate_slug", :as => 'validate_slug'
      post "/companies/subscribe", :to => "companies#subscribe", :as => 'subscribe'
      patch "/companies/unsubscribe", :to => "companies#unsubscribe", :as => 'unsubscribe'
      post "/companies/bookmark", :to => "companies#bookmark", :as => 'bookmark'
      post :validate_user, :to => "companies#validate_user", :as => 'validate_user'
      patch "/companies/bookmarked", :to => "companies#bookmarked", :as => 'bookmarked'
      get :view, :to => "companies#view_companies", :as => 'view'
      get "view/:category-in-:location", :to => "companies#view_companies" , :as => 'company_location'
      post "/companies" => "companies#create"
      get "/companies" => "companies#index"
      post "/companies" => "companies#index"
      get 'posts',:to => "blog_posts#index"
      post 'posts', :to => "blog_posts#index"
      get 'unpublished_posts',to: "blog_posts#unpublished_posts"
      get 'visible_to_followers_posts', to: "blog_posts#visible_to_followers_posts"
      get 'all-posts', to: "blog_posts#all_posts"
      get 'trending-featured-posts', to: 'blog_posts#trending_posts'
      # get "/remove_featured_image/:id" => "blog_posts#remove_featured_image"
    end
      get 'users', :to => 'users#index' , :as => 'users'
      post 'users', :to => 'users#index' 
    resources :users , :path => "" , only:[:show] do
      collection do
        # get ':id',  controller: "users", action: "show" , :as => "user"
        post :follow, :to => "users#follow", :as => 'users/follow'
        patch :unfollow, :to => "users#unfollow", :as => 'users/unfollow'
      end
    end
    # Nested collection route for companies
    resources :albums, only:[:show]

    resources :testimonials, only:[:show]
  end
  resources :blog_posts, :path => '', only:[:index]  do
    collection do
      get ':company_id/tag/:tag_name',to: "blog_posts#show_tags_blog_posts", :as => "tag_name"
      get ':company_id/category/:category_name', to: "blog_posts#show_category_blog_posts", :as => "category_name"
      get ':company_id/:user_id/:id',  controller: "blog_posts", action: "show" , :as => "blog_post"
    end  
  end
end

app/models/company.rb
require 'uri'
class Company < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "235x200>", thumb: "130x120>", small: "50X45>"}, default_url: "missing.png"
  has_attached_file :cover_photo, styles: { medium: "1280x960>", thumb: "828x315>", small: "235x200>"}, default_url: "cover_dummy.jpg"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :albums , :dependent => :destroy
  has_many :testimonials, -> {where deleted: 0}, :dependent => :destroy
  before_create :default_values
  has_many :users
  before_create :make_slug
  belongs_to :company_size_group
  belongs_to :city
  belongs_to :functional_area
  has_many :blog_posts
  has_many :company_followers
  has_many :user_followers
  has_many :views, :foreign_key => :object_id,:dependent => :destroy
  validates :website, presence: true,  :uniqueness => true
  # validates :primary_email, :uniqueness => true
  
  #add By default value
  def default_values
    self.status ||= '1'
    self.verified ||= "1"
  end

  # Helper method to generate slugs for companies
  def strip_url(target_url)
    target_url.to_s.downcase.gsub("http://", "")
    .to_s.downcase.gsub("https://", "")
    .to_s.downcase.gsub("www.", "")
  end

  # method to generate slugs for companies
  def make_slug
    self.slug = strip_url(self.website).split(".").first
  end

  # Method to use slug instead of id
  def to_param
    slug
  end

  #  search company
  def self.search_company( args )
    keys = []
    values = []
    params = args[:params]
    order = args[:order]

    params.each do |k , v|
      if v.present?
        key = (k == "name") ? "#{k} like (?)" : "#{k} IN (?)"
        keys.push(key)
        value = (v == "name") ? "%#{v}%" : v
        values.push(value)
      end
    end
    conditions = values
    conditions.unshift(keys.join(" and "))
    if order == "new_added"
      self.where(conditions).order("created_at DESC").where("status" => 1)
    else
      sql = self.joins(:views).select("companies.*, count(views.id) as view_count").where(conditions).where("views.view_type_id" => 2, "status" => 1).group('views.object_id').order("count(views.id) desc")
#      abort(sql.length.inspect)
    end
  end

   #Recent add Company
   def self.recent_add
     self.all.order("created_at DESC LIMIT 6").where("status" => 1)
   end

   #show most viewd company
   def self.most_view
      self.joins(:views).select("companies.*, count(views.id) as view_count").where("views.view_type_id" => 2, "status" => 1).group("views.object_id").order("count(views.id) desc LIMIT 6")
   end

   def self.search(params)
    scope = all
    scope.where!(functional_area_id: params[:category]) if params[:category]
    scope.where!(city_id: params[:location]) if params[:location]
    scope.recent_add
    scope.most_view
    scope.all

    # ...
  end

end

app/controllers/admin/companies_controller.rb
=begin
  Namespace : Admin
  Controller: CompaniesController
  Created By: Zafar
  Description: Controller dedicated to CRUD displayed in admin section for companies
=end
class Admin::CompaniesController < Admin::AdminController
  before_action :set_company, only: [:show, :edit, :update, :destroy,:search,:follow,:index]
  before_action :authenticate_user!
  before_action :pundit_authorize , except: [:validate_user , :user_invitation]
  skip_before_action :authenticate_user!, :only => :show

  # check auhorized action
  def pundit_authorize
    authorize [:admin, @company||:company]
  end

  # GET /companies
  # GET /companies.json
  #!is_super_admin? use to check user is super admin or not
  def index
    @company = Company.new
    @city = City.all
    @company_size_groups = CompanySizeGroup.all
    @functional_area= FunctionalArea.all
    if is_super_admin?
      @companies = Company.where(:status => 1)
    elsif is_admin?
      @companies = Company.where(:user_id => current_user.id)
    else
      @companies = Company.where(:id => current_user.company_id).where(:status => 1)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find_by_slug(params[:id])
    @album = Album.new(:company_id => @company.id)
    @testimonial = Testimonial.new(:company_id => @company.id)
    @testimonials = @company.testimonials
    @company_size_groups = CompanySizeGroup.all
    @functional_area= FunctionalArea.all
    @city = City.all
    @albums = @company.albums
    @data = {:type => "company_view", :object_id => @company.id ,:ip => request.remote_ip, :user => user_signed_in? ? current_user.id : "" }
    @view = View.track_view(@data)
    if user_signed_in?
      @follow_status = CompanyFollower.where( :user_id => current_user.id, :company_id => @company.id, :followed => 1).count
      @bookmark_status = CompanyFollower.where( :user_id => current_user.id, :company_id => @company.id, :bookmarked=> 1).count
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /companies/new
  #!is_super_admin? use to check user is super admin or not
  def new
    @user = User.where.not(:role_id => 1).where(company_id: nil)
    @city = City.all
    @company =  Company.new
    @company_size_groups = CompanySizeGroup.all
    @functional_area= FunctionalArea.all
  end

  # GET /companies/1/edit
  def edit
    @city = City.all
    @company_size_groups = CompanySizeGroup.all
    @functional_area= FunctionalArea.all
    @user = User.where.not(:role_id => 1)
  end

  # POST /companies
  # POST /companies.json
  def create
    @city = City.all
    @company_size_groups = CompanySizeGroup.all
    @functional_area= FunctionalArea.all
    @company = Company.new(company_params)
     respond_to do |format|
      if @company.save
        if is_admin? && current_user.company == nil
          current_user.update_attributes(:company_id => @company.id)
        end
        if params[:company][:user_id].present?
          @company.update_attributes(:user_id => params[:company][:user_id] )
          @user = User.find_by(id: params[:company][:user_id])
          if @user.present?
            @user.update_attributes(:company_id => @company.id)
            if @user.role_id != "3"
              @user.update_attributes(:role_id => "3")
            end
          else
            @user = User.create(:email => params[:company][:user_id])
            @user.invite!
          end

          format.html { redirect_to edit_admin_company_path(@company), notice: 'Company was successfully created.' }
          format.json { render :show, status: :created, location: @company }
        else
          format.html { redirect_to edit_admin_company_path(@company), notice: 'Company was successfully created.' }
          format.json { render :show, status: :created, location: @company }
        end
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @city = City.all
    @company_size_groups = CompanySizeGroup.all
    @functional_area= FunctionalArea.all
    respond_to do |format|
      if @company.update(company_params)
        if is_admin? && current_user.company == nil
          current_user.update_attributes(:company_id => @company.id)
        end
        if params[:company][:user_id].present?
          @company.update_attributes(:user_id => params[:company][:user_id])
          @user = User.find_by(id: params[:company][:user_id])
          user= @user.role_id.split(",")
          if !user.include?("3")
            user << "3"
          end
          @user.update_attributes({:company_id => @company.id,:role_id => user.join(",")})
          format.html { redirect_to edit_admin_company_path(@company), notice: 'Company was successfully updated.' }
          format.json { render :show, status: :created, location: @company }
        else
          format.html { redirect_to edit_admin_company_path(@company), notice: 'Company was successfully updated.' }
          format.json { render :show, status: :created, location: @company }
        end
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.update(status: '0')
    respond_to do |format|
      format.html { redirect_to admin_companies_path, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #Validation on Slug
  def validate_slug
    website = params[:company][:website]
    slug = strip_url(website).split(".").first
    slug_flag = Company.where(:slug => slug).count
    status = (slug_flag > 0) ? false : true
    render json: {:status => status}
  end

   #Validation on User
  def validate_user
    user = params[:company][:user_id]
    user_count = Company.where(:user_id => user).count
    status = (user_count > 0) ? false : true
    render json: {:status => status}
  end


  # function to follow a company
  def follow
    @data = {:user_id =>  current_user.id, :company_id => params[:company_id], :followed => 1}
    status = CompanyFollower.follow(@data)
    status = status ? true :false
    render json: {:status => status}
  end

  # function to un-follow a company
  def unfollow
    @data = {:user_id =>  current_user.id, :company_id => params[:company_id]}
    status = CompanyFollower.unfollow(@data)
    status = status ? true :false
    render json: {:status => status}
  end

  #function to bookmark a company
  def bookmark
     @data = {:user_id =>  current_user.id, :company_id => params[:company_id], :bookmarked => 1}
    status = CompanyFollower.bookmark(@data)
    status = status ? true :false
    render json: {:status => status}
  end

  #function to upadate bookmark
  def bookmarked
    @data = {:user_id =>  current_user.id, :company_id => params[:company_id]}
    status = CompanyFollower.bookmarked(@data)
    status = status ? true :false
    render json: {:status => status}
  end

  private
  # Use callback to share common setup or constraints between actions.
  def set_company
    @company = Company.find_by_slug(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:name, :functional_area_id,:user_id,:owner_name, :website,:overview,:company_size_group_id,:founded, :latitude, :longitude , :primary_email, :secondary_email, :primary_contact_number, :secondary_contact_number, :contact_person, :city_id, :address,:logo,:cover_photo).merge(user_id: current_user.id)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper

end

app/views/companies/index.html.erb
<%= provide(:title, "Listing Companies") %>
<div class="main">
  <div class="company-banner-section">
    <div class="banner-title">
    <div class="container favourite-company better-company">
      <h1>Know your</h1>
      <h2>favourite companies better</h2>
        <div class="banner-form">
          <%= form_tag companies_path, :method => "get" ,  data: { turbolinks: false },  enforce_utf8: false  do %>
            <div class="form-group">
              <%= label_tag :locations %>
              <%= select_tag 'city_id', options_for_select(@city.collect{ |u| u.name},  selected: params[:city_id]  ) , {:include_blank => 'Select Location', class: "form-control"}%>
              <i class="fa fa-sort-down"></i>
            </div>
            <div class="form-group">
              <%= label_tag :Categories %>
              <%= select_tag 'functional_area_id',
              options_for_select(@functional_area.collect{|a| a.name }, selected: params[:functional_area_id] ), {:include_blank => 'Select Category', class: "form-control"} %>
              <i class="fa fa-sort-down"></i>
            </div>
            <span class="sort-slider">Sort</span> 
            <div class="slideshow-container">
              <div class="mySlides">
                <h3>New Added</h3>
              </div>
              <div class="mySlides">
               <h3>Most Viewed</h3>
              </div>
              <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
              <a class="next" onclick="plusSlides(1)">&#10095;</a>
            </div>
          <% end %>
            <button type="submit" value="Search Companies" class="btn" id="generate-url" data-turbolinks="false">Search Companies</button>
        </div>
      </div>
    </div><!-- banner-title -->
  </div><!-- company-banner-section-->
  <div class="container p-0">
    <div class="company-second-section added-companies">
      <h3><span class="position-relative">Recently Added Companies</span></h3>
      <div class="popular-locations">
        <ul>
          <li>Popular Locations:</li>
          <li><a href="#">Chandigarh </a></li>
          <li><a href="#">Mohali</a></li>
          <li><a href="#">Delhi </a></li>
        </ul>
      </div>
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <% @recent_add.each do |recent_add|%>
            <% if recent_add.present? %>
              <div class="swiper-slide">
                <div class=" company-blog-div">
                  <a href="<%= company_path(recent_add)%>">
                    <div class="company-inner-blog">
                      <div class="blog-image">
                        <% if recent_add.logo.present? %>
                          <img src="<%= recent_add.logo.url %>">
                        <%else%>
                          <img src="/assets/<%= recent_add.cover_photo.url %>">
                        <%end%>
                      </div>
                      <h4><%= recent_add.name %></h4>
                      <p class="heading-text"><%= truncate(strip_tags(recent_add.overview), length: 100)+ "..."%></p>
                      <p class="location-div"><span><i class="fa fa-map-marker" aria-hidden="true"></i><%= @city.find(recent_add.city_id).name %></span><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                      </p>
                    </div>
                  </a>
                </div>
              </div>
            <%end%>
          <%end%>
        </div>
        <div class="swiper-button-next"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
        <div class="swiper-button-prev"><i class="fa fa-arrow-left" aria-hidden="true"></i></div>
        <div class="swiper-scrollbar"></div>
      </div>
    </div><!-- added-companies -->
  </div><!--container-->

  <div class="container p-0">
    <div class="brows-company-section">
      <h3><span  class="position-relative">Browse Companies by Categories</span></h3>
      <div class="row">
        <div class="col-md-4">
          <div class="comp-categories">
            <ul class="catogories-inner">
              <li><a class="active" href="#">Information Technology</a></li>
              <li><a href="#">DBA</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="comp-categories">
            <ul class="catogories-inner">
              <li><a href="#">Human Resources</a></li>
              <li><a href="#">Networking</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="comp-categories">
            <ul class="catogories-inner">
              <li><a href="#">Software Development</a></li>
              <li><a href="#">Networking</a></li>
            </ul>
          </div>
        </div>
      </div><!-- row-->
    </div><!-- brows-company-section-->
  </div><!-- container-->

  <div class="container p-0">
    <div class="company-second-section added-companies mt-0">
      <h3 class="position-relative border-top-0"><span class="position-relative">Most Viewed Companies</span></h3>
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <% @most_view.each do |most_view|%>
            <% if most_view.present? %>
              <div class="swiper-slide">
                <div class=" company-blog-div">
                  <a href="<%= company_path(most_view)%>">
                    <div class="company-inner-blog">
                      <div class="blog-image">
                        <% if most_view.logo.present? %>
                          <img src="<%= most_view.logo.url %>">
                        <%else%>
                          <img src="/assets/<%= most_view.cover_photo.url %>">
                        <%end%>
                      </div>
                      <h4><%= most_view.name %></h4>
                      <p class="heading-text"><%= truncate(strip_tags(most_view.overview), length: 100)+ "..."%></p>
                      <p class="location-div"><span><i class="fa fa-map-marker" aria-hidden="true"></i><%= @city.find(most_view.city_id).name %></span><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                      </p>
                    </div>
                  </a>
                </div>
              </div>
            <%end%>
          <%end%>
        </div>
        <div class="swiper-button-next"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
        <div class="swiper-button-prev"><i class="fa fa-arrow-left" aria-hidden="true"></i></div>
        <div class="swiper-scrollbar"></div>
      </div>
    </div><!-- added-companies -->
  </div><!--container-->
</div><!-- main -->

<script>

    var slideIndex = 1;
      showSlides(slideIndex);

      function plusSlides(n) {
        showSlides(slideIndex += n);
      }

      function currentSlide(n) {
        showSlides(slideIndex = n);
      }

      function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) {slideIndex = 1}    
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";  
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";  
        dots[slideIndex-1].className += " active";
      }

</script>

app/views/companies/index.js.slim
| $('#company_list').html('
= j render("companies/includes/companies")
| ');

app/views/companies/show.html.erb
<% provide(:title, "Company | " + @company.name) %>
<!-- <div class="main"> -->
<!--banner section ---->
<section id="tabs-banner-section">
  <div>
    <div class="container">
      <div class="row no-gutters">
        <div class="col-md-3 col-sm-4 nav-tabs-bg">
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-overview-tab" data-toggle="pill" href="#v-pills-overview" role="tab" aria-controls="v-pills-home" aria-selected="true"><span>Overview</span></a>
            <a class="nav-link" id="v-pills-details-tab" data-toggle="pill" href="#v-pills-details" role="tab" aria-controls="v-pills-profile" aria-selected="false"><span>Details</span></a>
            <a class="nav-link" id="v-pills-loaction-tab" data-toggle="pill" href="#v-pills-location" role="tab" aria-controls="v-pills-messages" aria-selected="false"><span>Location</span></a>
          </div>
        </div>
        <div class="col-md-9 col-sm-8 tab-content-bg">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-overview" role="tabpanel" aria-labelledby="v-pills-overview-tab">
              <div class="row">
                <div class="col-md-6">
                  <h1>Lorem Ipsum</h1>
                </div>
                <div class="col-md-6">
                  <% if user_signed_in? %>
                    <div class="subscribe-buttons">
                      <% follow_text = ( @follow_status == 0 ) ? "subscribe" : "unsubscribe" %> 

                      <a href="javascript:void(0);" class="btn <%= follow_text %>" data-company='<%= @company.id %>' id="follow_button" title="Select-subscribe"><%= follow_text %></a>
                      <% if @bookmark_status == 0 %>
                        <a href="#" class="bookmark bookmark_button" data-company='<%= @company.id%>' ><i class="fa fa-bookmark-o" title="bookmark" aria-hidden="true"></i></a>
                      <%else%>
                        <a href="#" class="unbookmark bookmark_button" data-company='<%= @company.id%>' ><i class="fa fa-bookmark" title="unbookmark" aria-hidden="true"></i></a>
                      <%end%>
                    </div>
                  <% end %>
   
                </div>
              </div>
              <div class="bigtext read-more-text">
                <p><%= strip_tags(@company.overview) %></p>
              </div>
              <div class="read-less-text bigtext">
                <p><%= truncate(strip_tags(@company.overview), length: 400) %></p>
              </div>
              <a class="read-more">Read More<i class="fa fa-chevron-down" aria-hidden="true"></i></a>
              <a class="read-less">Read Less<i class="fa fa-chevron-up" aria-hidden="true"></i></a>
            </div>
            <div class="tab-pane fade" id="v-pills-details" role="tabpanel" aria-labelledby="v-pills-details-tab">
              <% if @company.present? %>
                <h1><%= @company.name%></h1>
                <table class="company-details-table" colspann="0" rowspan="0" border="0">
                  <tbody>
                    <%= render 'companies/includes/company_detail' %>
                  </tbody>
                </table>
              <%end%>
            </div>
            <div class="tab-pane fade location-tab" id="v-pills-location" role="tabpanel" aria-labelledby="v-pills-location-tab">
              <!-- <div id="map"> -->
              <!-- <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3430.250697779677!2d76.68776721470148!3d30.711351881644607!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fee5570d79905%3A0xed9e2f79535c8a94!2sUimatic!5e0!3m2!1sen!2sin!4v1531477518274" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe> -->
             <%= render 'companies/includes/location'%>
              <!-- </div> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- bottom company posts section ---->
<section id="company-posts">
  <div class="container">
    <div class="">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <a class="nav-item nav-link active" id="nav-company-users-tab" data-toggle="tab" href="#company-users" role="tab" aria-controls="company-users" aria-selected="true">Company Users</a>
          <a class="nav-item nav-link" id="nav-company-profile-tab" data-toggle="tab" href="#company-profile" role="tab" aria-controls="company-profile" aria-selected="false">Company Posts</a>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane company-users-tab fade show active" id="company-users" role="tabpanel" aria-labelledby="nav-company-users-tab">
          <h1 class="company-post-main-title">Users</h1>
          <% @users.in_groups_of(3).each do|users| %>
            <div class="row">
              <% users.each do|user| %>
                <% if user.present? %>
                  <div class="col-md-4 company-blog-div">
                    <div class="company-inner-blog">
                      <% first_name = user.first_name %>
                      <% last_name = user.last_name %>
                      <% if first_name.present? && last_name.present? %>
                        <h3><%= first_name+ " " +last_name %></h3>
                      <%else%>
                         <h3><%= user.username %></h3>
                      <%end%>
                      <table class="usr-prfl" cellpadding="0" cellspacing="0" border="0">
                        <tbody>
                          <tr>
                            <td width="92px" class="lt-side">User name</td>
                            <td class="rt-side"><%= user.username %></td>
                          </tr>
                          <tr>
                            <td class="lt-side">Email</td>
                            <td class="rt-side"><%= user.email %></td>
                          </tr>
                        </tbody>
                      </table>
                      <% company = user.company %>
                      <a href="<%= company_user_path(company, user) %>" class="view-profile">View Profile</a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div><!-- row ends --->
          <% end %>
        </div>
        <div class="tab-pane fade" id="company-profile" role="tabpanel" aria-labelledby="nav-company-profile-tab">
          <div id="companies-posts">
            <%= render 'companies/includes/company_posts'%>
          </div>
        </div>
      </div>
    </div>
  </div>
<%= will_paginate @company_posts %>
  
</section>