config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'settings/unsubscribe'
    patch 'settings/update'
  end

  root to: 'blog_posts#index'
  devise_for :users , :controllers => { :omniauth_callbacks => "omniauth_callbacks" , :invitations => "invitations" }, :skip => [:registration]
  devise_scope :user do
    # using login path for registration
    get '/users/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    get '/users/edit' => 'registrations#edit', :as => :edit_user_registration
    put '/users' => 'registrations#update' 
    patch '/users' => 'registrations#update' 
    delete '/users' => 'registrations#destroy'
  end
  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
  resources :images
  resources :post_categories, :path => 'categories',  only:[:index, :show]
  resources :user_notification_preferences , :path => 'user/preferences' do
      collection do 
        get 'unsubscribe'
        patch 'update'

      end
  end
  # resources :users do
  #   collection do
  #     post :follow, :to => "users#follow", :as => 'users/follow'
  #     patch :unfollow, :to => "users#unfollow", :as => 'users/unfollow'
  #   end
  # end
  as :user do
    post :validate_useremail , :to => "users#validate_useremail", :as => 'validate_useremail'
  end

  # Routes for admin dashboard starts here
  namespace :admin, :path => "/dashboard" do
    get 'companies/posts',:to => "blog_posts#index"
    post 'companies/posts',:to => "blog_posts#index"
    post :unfollow_company, :to => "users#unfollow_company" , :as => '/unfollow_company'
    post :unfollow_user , :to => "users#unfollow_user" , :as => '/unfollow_user'
    post :remove_bookmark, :to => "users#remove_bookmark", :as => '/remove_bookmark'
    post "validate_blog_post_slug" => "blog_posts#validate_blog_post_slug"
    # post '/user' , :to => "users#index"
    get "/remove_featured_image/:id" => "blog_posts#remove_featured_image"
    resources :user_notification_preferences , :path => 'user/preferences' do 
      collection do 
        get 'edit_multiple'
        patch 'update'

      end
    end
    resources :users do
      post 'admin/users' , :to => "blog_post#index"
      collection do
        get :followed_companies, :to => "users#followed_companies", :as => '/folllowed_companies'
        get :bookmarked_companies, :to => "users#bookmarked_companies", :as => '/bookmarked_companies'
        get :followed_users, :to => "users#followed_users", :as => '/followed_users'
        get :newsletter_enable_status, :to => "users#newsletter_enable_status", :as => "/newsletter_enable_status"
        patch :update_newsletter_status, :to => "users#update_newsletter_status"
      end
    end
    resources :newsletters
        get '/newsletter/unsubscribe', :to => "newsletters#unsubscribe" , :as => "unsubscribe"
        # post :unsubscribe, :to => "newsletters#unsubscribe"
    resources :roles do
      collection do
        get "role" => "roles#show_roles"
        post 'roles/assign'
      end
    end
    resources :admin, :path => '', only:[:index]
      resources :companies, :path => "companies" ,except:[:show] do
      
        collection do
          post :validate_user, :to => "companies#validate_user", :as => 'validate_user'
        end
        resources :albums
        resources :testimonials
        resources :blog_posts, :path => '/posts', except:[:show]  do
          collection do
            post "upload_post_image" => "blog_posts#upload_post_image"
            get 'drafts'   => "blog_posts#draft_posts"
            get 'tag/:tag_name' => "blog_posts#show_tags_blog_posts", :as => "tag"
            get 'category/:category_name' => "blog_posts#show_category_blog_posts", :as => "category"
          end
      end
    end
    resources :images
    resources :post_categories , :path => '/post/categories',  except:[:show]
  end
  # Routes for admget 'users', :to => 'users#index' , :as => 'users'in dashboard ends here
  
  # routes for Companies, omitting path (controller name)
  resources :companies , :path => "" ,only:[:show,:index] do
    collection do
      post :validate_slug , :to => "companies#validate_slug", :as => 'validate_slug'
      post "/companies/subscribe", :to => "companies#subscribe", :as => 'subscribe'
      patch "/companies/unsubscribe", :to => "companies#unsubscribe", :as => 'unsubscribe'
      post "/companies/bookmark", :to => "companies#bookmark", :as => 'bookmark'
      post :validate_user, :to => "companies#validate_user", :as => 'validate_user'
      patch "/companies/bookmarked", :to => "companies#bookmarked", :as => 'bookmarked'
      get :view, :to => "companies#view_companies", :as => 'view'
      get "view/:category-in-:location", :to => "companies#view_companies" , :as => 'company_location'
      post "/companies" => "companies#create"
      get "/companies" => "companies#index"
      post "/companies" => "companies#index"
      get 'posts',:to => "blog_posts#index"
      post 'posts', :to => "blog_posts#index"
      get 'unpublished_posts',to: "blog_posts#unpublished_posts"
      get 'visible_to_followers_posts', to: "blog_posts#visible_to_followers_posts"
      get 'all-posts', to: "blog_posts#all_posts"
      get 'trending-featured-posts', to: 'blog_posts#trending_posts'
      # get "/remove_featured_image/:id" => "blog_posts#remove_featured_image"
    end
      get 'users', :to => 'users#index' , :as => 'users'
      post 'users', :to => 'users#index' 
    resources :users , :path => "" , only:[:show] do
      collection do
        # get ':id',  controller: "users", action: "show" , :as => "user"
        post :follow, :to => "users#follow", :as => 'users/follow'
        patch :unfollow, :to => "users#unfollow", :as => 'users/unfollow'
      end
    end
    # Nested collection route for companies
    resources :albums, only:[:show]

    resources :testimonials, only:[:show]
  end
  resources :blog_posts, :path => '', only:[:index]  do
    collection do
      get ':company_id/tag/:tag_name',to: "blog_posts#show_tags_blog_posts", :as => "tag_name"
      get ':company_id/category/:category_name', to: "blog_posts#show_category_blog_posts", :as => "category_name"
      get ':company_id/:user_id/:id',  controller: "blog_posts", action: "show" , :as => "blog_post"
    end  
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  
  belongs_to :user 
  belongs_to :company 
  has_many :images , :dependent => :destroy
  has_many :views
  before_create  :default_values  
  validates_uniqueness_of :name
  validates :name, :uniqueness => true
  
  # For deleted field the default is false
  def default_values
    self.deleted ||= '0'
  end
  
  # For slug generation
  def to_param
    [name.parameterize].join("-")
  end
  
  # Method to find by name instead id
  def self.find_by_param(name)
    name = name.gsub("-", " ")
    where("lower(name) = ?", name).first
  end
  
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	belongs_to :company
  has_many :blog_posts_post_categories
	has_many :post_categories, :through => :blog_posts_post_categories
	has_many :blog_post_images
  belongs_to :blog
  belongs_to :user
  has_many :views
	has_attached_file :featured_image, styles: { medium: "235x157>", thumb: "130x120>", small: "50X45>"}, default_url: '/assets/missing_:style.png'
	validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\z/
  before_validation :strip_whitespace
  before_create :create_slug
  # after_save :schedule
  # before_create :schedule
	scope :all_posts, -> {where(deleted: 0, publish: 1)}
	scope :published_posts, -> {where(deleted: 0, publish: 1)}
  scope :private_posts , -> { where(deleted: 0 ,private: 1)}
  # scope :subscribed, ->(company_followers) { where(user_id: company_followers) }
  # validates :slug, :presence => true,  :uniqueness => true

  # after_save :update_slug
  def to_param
    slug
  end

  # method to remove white space between tags
  def strip_whitespace
    self.tags = tags.gsub(/\s+/, '')
    # self.tags = tags.strip
    self.title =  title.strip
    self.description = description.strip
    # self.keywords = keywords.strip
    self.body = body.strip
  end

  # method to create unique slug recursively
  def create_slug
    var_slug = [title.parameterize].join("-")
    self.slug = BlogPost.generate_slug(var_slug)
  end

  #recursive method for generating slug
  def self.generate_slug(var_slug, count = 0)
    created_slug = (count == 0) ? var_slug : var_slug+ "-" +"#{count}"
    new_slug = BlogPost.where(:slug => created_slug).count()
    if (new_slug > 0)
      count =count + 1
      generate_slug(var_slug, count)
    else
      return created_slug
    end
  end

  # def schedule
  #   debugger
  #   if self.publish == false
  #     debugger
  #     SchedulePostJob.perform_later(self)
  #   end
  # end


  #  def publish
  #   unless self.publish == "0"
  #     self.update_attributes(publish: "1")
  #   end
  # end

  
   def self.search(params)
    # scope = all
    # scope.where!(functional_area_id: params[:category]) if params[:category]
    # scope.where!(city_id: params[:location]) if params[:location]
    # scope.recent_add
    # scope.most_view
    # scope.all

    # ...
  end
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < Admin::AdminController
  before_action :set_company , only: [:new, :show, :edit, :update, :destroy, :create, :index]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :pundit_authorize , except: [:upload_post_image,:validate_blog_post_slug, :remove_featured_image, :draft_posts]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, :only => :show

  # check auhorized action
  def pundit_authorize
    unless is_super_admin?
      authorize [:admin, @blog_post || @company.blog_posts.new]
    end
  end
  

  # GET /posts
  # GET /posts.json
  def index
    conditions = {:deleted => 0}
    conditions[:publish] = 1 unless is_super_admin?
    conditions[:company_id] = @company.id if params[:company_id].present?
    conditions[:publish] = params[:publish] if params[:publish].present?
    params[:page] = 1 unless params[:page].present?

    @blog_posts = BlogPost.where(conditions).order('created_at DESC')
    @companies = Company.all
  end

  # GET /posts/new
  def new
    @categories = PostCategory.where(:status => "1").where(:deleted => "0")
    @user = User.where.not(:role_id => 1)
    @companies = Company.all
    if params[:company_id].present?
      @company = Company.find_by_slug(params[:company_id])
      # check_company_access
      @blog_post = BlogPost.new(:company_id => @company.slug)
    else
      @blog_post = BlogPost.new()
    end
  end

  # GET /posts/1
  def show
    @company = Company.find_by_slug(params[:company_id])
    @blog_post = BlogPost.find_by_slug(params[:id])
  end

  # GET /posts/category/category_name
  def show_category_blog_posts
    # @blog_posts =  PostCategory.find_by_name(to_de_param(params[:category_name])).blog_posts.where(:deleted => "0").where(:publish => "1").order('updated_at DESC').paginate(:page => params[:page], :per_page => 5)
    @blog_posts= PostCategory.where("find_in_set(?, post_category_ids)", to_de_param(params[:category_name])).blog_posts.where(:deleted => "0").where(:publish => "1").order('updated_at DESC').paginate(:page => params[:page])
  end

  #GET /posts/tag/tags_name
  def show_tags_blog_posts
    @blog_posts= BlogPost.where("find_in_set(?, tags)", to_de_param(params[:tag_name])).where(:deleted => "0").where(:publish => "1").order('updated_at DESC').paginate(:page => params[:page])
    #@blog_posts= BlogPost.where("tags like ?", "%#{params[:tag_name]}%")
  end

  # GET /posts/1/edit
  def edit
    @companies = Company.all
    @categories = PostCategory.where(:status => "1").where(:deleted => "0")
  end

  # POST /posts
  # POST /posts.json
  def create
    @company = Company.find_by_slug(params[:company_id])
    @blog_post =  BlogPost.new(blog_post_params)
    respond_to do |format|
      if @blog_post.save
       # time = Time.strptime(params[:blog_post][:published_at], '%m/%d/%Y %H:%M')
       # @blog_post.update_attributes(:published_at => time)
        if is_user?
          params[:user_id] = current_user.id
        else
          params[:user_id] = @company.user_id
        end
        params["image_ids"] = params["image_ids"].split(",")
        @blog_post.update_attributes(:user_id => params[:user_id])
        @blog_post_image = BlogPostImage.where(id: params["image_ids"])
        @blog_post_image.update_all(:blog_post_id => @blog_post.id ) if @blog_post_image.present?
        if params[:commit] == "Save and Publish"
          @blog_post.update_attributes(:publish => "1")
        else
          @blog_post.update_attributes(:publish => "0")
        end
        format.html { redirect_to edit_admin_company_blog_post_path(@company, @blog_post), notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @blog_post = BlogPost.find_by_slug(params[:id])
    @blog_post.post_category_ids = post_category_params[:post_category_ids]
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        if params[:blog_post][:company_id].present?
          @blog_post.update_attributes(:company_id => params[:blog_post][:company_id])
        end
        params[:user_id] =  is_user? ? current_user.id : @company.user_id
        @blog_post.update_attributes(:user_id => params[:user_id])
        if params[:commit] == "Save and Publish"
          @blog_post.update_attributes(:publish => "1")
        else
          @blog_post.update_attributes(:publish => "0")
        end
        params["image_ids"] = params["image_ids"].split(",")
        @blog_post_image = BlogPostImage.where(id: params["image_ids"])
        @blog_post_image.update_all(:blog_post_id => @blog_post.id ) if @blog_post_image.present?
        format.html { redirect_to edit_admin_company_blog_post_path(@company,@blog_post), notice: 'Blog Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :back }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.JSON
  def destroy
  	@blog_post = BlogPost.find_by_slug(params[:id])
    @blog_post.update(deleted: '1')
    respond_to do |format|
      format.html { redirect_to admin_company_blog_posts_path, notice: 'Blog Post was successfully destroyed.' }
    end
  end

  # function to upload a blog post image in ckeditor
  def upload_post_image
    @image = BlogPostImage.new(:blog_post_image => params[:blog_post_image])
    respond_to do |format|
      if @image.save
        format.js {
          render json: {:img_url => @image.blog_post_image.url(), :med_img_url => @image.blog_post_image.url('medium'), :image_id => @image.id }
        }
      else
        render json: "error"
      end
    end
  end

  #method to remove featured image
  def remove_featured_image
    @blog_post = BlogPost.find_by_slug(params[:id])
      if @blog_post.update_attributes(featured_image: nil)
        render json: {:status => true}
      else
        render json: {:status => false}
      end
  end

  # to show draft posts
  def draft_posts
    @blog_posts = BlogPost.where(:deleted => '0').where(:company_id => current_user.company_id).where(:publish => "0").order('created_at DESC').paginate(:page => params[:page])
  end

  #check company access
  def check_company_access
    if @company.present? && @company.user_id == current_user.id && !is_super_admin?
          redirect_to admin_admin_index_path
    end
  end
  
  def validate_blog_post_slug
    slug_found = BlogPost.where(slug: params[:blog_post][:slug]).count 
    if slug_found > 1
      message = slug_found ? "ERROR" : "SUCCESS"
      render json: {message: message}
    else
      render json: {status: true  }
    end
  end  

private
  # for slug generation
  def to_de_param(str)
    str.split("-").join(" ")
  end

  # blog posts identification
  def set_blog_post
    unless @blog_post = BlogPost.where(slug: params[:id], company_id: @company.id).first
      redirect_to admin_admin_index_path, notice: "Blog post not found"
    end
  end

  # company identification
  def set_company
    @company = Company.find_by_slug(params[:company_id])
    if !is_super_admin? && @company.nil?
      redirect_to admin_admin_index_path, notice: "You don't have a company yet."
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_post_params
  	params.require(:blog_post).permit(:title,:user_id,:private,:visible_to_followers, :published_at, :tags,:description,:body,:keywords,:featured_image,:slug, :publish,:blog_id,:user_id, :post_category_ids => []).merge( :company_id => @company.id)
  end

  # post category permitted params
  def post_category_params
    params.require(:blog_post).permit(:post_category_ids => [] )
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/admin/blog_posts/_form.html.erb
<!-- <script src="//cdn.ckeditor.com/4.4.3/full-all/ckeditor.js"></script>
<script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script> -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.10/font/summernote.ttf" >
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.10/font/summernote.woff">


<div class="container">
  <div class="row">
    <div class="col-sm-7">
      <%= form_for [:admin, @company, @blog_post],  :html => {:class => "form_blog_post"}, data: { turbolinks: false } do |f| %>
        
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, :class => "form-control" , :placeholder => "Enter the title"%>
        </div>
        <%if params[:action] == "edit" %>
          <div class="form-group">
            <%= f.label :slug %>
            <%= f.text_field :slug, :class => "form-control" , :placeholder => "Change slug"%>
          </div>
        <%end%>
        <div class="form-group">
          <%= f.label "Tag Line" %>
          <%= f.text_area :description, :class => "form-control", length:'120' %>
        </div>
        <div class="form-group">
          <%= f.label "Body" %>
          <%= f.text_area :body, :class => "form-control summernote ", length:'120' %>
        </div>
        <div class="form-group">
          <%= f.label "Category" %><br>
          <%= f.select('post_category_ids', PostCategory.where(status: "1", deleted: "0").map{ |a| [a.name,a.id] }, {:selected => f.object.post_category_ids , disabled: "0" , :unique => true},{:class => "form-control", :multiple => true  }) %>
        </div>
        <div class="form-group">
          <%= f.label "Tags" %>
          <%= f.text_field :tags, :placeholder => "Enter tags", :class => "form-control" %>
        </div>
        <div class="form-group hidden">
          <%= f.hidden_field :keywords %>
        </div>
        <!-- <div class="form-group">
          <%#= f.label "Schedule Date and time" %>
                <div class='input-group date' id='datetimepicker1'>
                    <%#= f.text_field :published_at , class: "form-control"%>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div> -->
        <div class="form-group">
          <%= f.label :featured_image %>
          <%= f.file_field :featured_image %>
          <% if params[:action] != "new" %>
            <% if @blog_post.featured_image.present? %>
              <%= image_tag(@blog_post.featured_image.url(:medium), :class => "valign", id:"featured_image_id") %>
              <span >
                <%= link_to 'Remove image', "#" ,data: { confirm: 'Are you sure?' } ,id:"remove_featured_image" %>
              </span>
            <% end%>
          <% end%>
        </div>
            <%= f.label :private_post %><br>
        <div class="form-group checkbox">
          <label>
            <% status = (params[:action] != "new" && @blog_post.private == true) ? true : false %>
              <%= f.check_box :private, :checked => status %>
              <%= f.label :private %>
          </label>
        </div>

         <%= f.label :visible_to_followers %><br>
        <div class="form-group checkbox">
          <label>
            <% status = (params[:action] != "new" && @blog_post.visible_to_followers == true) ? true : false %>
              <%= f.check_box :visible_to_followers, :checked => status %>
              <%= f.label :visible_to_followers %>
          </label>
        </div>
       <!--  <%#if is_manager? || is_super_admin?%>
          <div class="form-group">
            <%#if (params[:action] != "new" && @blog_post.publish == true) %>
              <%#= f.check_box :publish ,:checked => true %>
              <%#= f.label :publish %>
            <%#else%>
              <%#= f.check_box :publish ,:checked => false %>
              <%#= f.label :publish %>
            <%#end%>
          </div>
        <%#end%> -->
        <div class="form-group">
          <%= f.submit "Save and Publish", :class => "btn btn-primary" %>
          <%= f.submit "Save as Draft" , :class => "btn btn-primary" %>
        </div>
        <div class="form-group">
          <%= hidden_field_tag "image_ids"  %>
        </div>
      <%end%>
      
      <div class="hidden">
        <%= form_tag upload_post_image_admin_company_blog_posts_path, :remote => true, :id => "blog_post_form_upload", class:"blog_post_upload_image_btn", :data => { :type => :json }, :authenticity_token => true, :multipart => true do %>
          <div class="form-group">
            <%= file_field_tag :blog_post_image, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  
<style>
.card-header.note-toolbar .note-color .dropdown-toggle {
    width: 20px;
    height: 30px;
    padding-left: 5px;
    }
    .content-wrapper {
      overflow:hidden;
    }
</style>  
<script>
 $('#blog_post_slug').on("blur", function(){
    var slug_val = $("#blog_post_slug").val().trim().toLowerCase().split(" ").join("-").replace(/-{2,}/g, '-')
    $('#blog_post_slug').val(slug_val);
  });
  // $('#datetimepicker1').datetimepicker();
</script>

app/views/admin/blog_posts/_show_blog_posts.html.erb
<h1>Listing Blog Posts</h1><br>
<% if is_super_admin?   %>
<br>
  <div class="container">
    <div class="form-group">
      <label class="col-lg-2 control-label">Select Company</label>
        <div class="col-lg-2" align="center">
          <%= select_tag 'company_id',options_for_select(@companies.map{|a| a.slug},  selected: params[:company_id]),{ :include_blank => "Select Company" , :class => "form-control"} %>
        </div>
      <label class="col-lg-2" align="center">Status</label>
        <div class="col-lg-2" align="center">
          <select name="publish" id="publish" class="form-control"  >
            <option value = "" > Status</option>
            <option value = "<%=1%>" > Publish</option>
            <option value = "<%=0%>"> Draft</option>
          </select>
        </div>
      <div class="col-lg-4">
        <div class="action">
          <%= submit_tag "Search Posts" , id: "search_posts" , :class => "btn btn-primary",name: nil %>
        </div>
      </div>
    </div>
  </div>
  <br>
<%end%>
<div class="filtered_content">
  <table class="table my_table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Category</th>
        <th><center>Company Name</center></th>
        <th><center>Status</center> </th>
        <th><center>Views</center></th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @blog_posts.each do |blog_post| %>
        <tr>
          <td><%= blog_post.title %></td>
          <td>
            <% @post_category = blog_post.post_categories.where(:status => "1").map(&:name) %>
      			<%= raw(@post_category.map{|cat| cat}.join(",") ) %>
          </td>
          <td align="center"><%= blog_post.company.slug%></td>
          <td align="center">
            <%= blog_post.publish ? "Published" : "Draft" %>
          </td>
          <td align="center">
            <% views = View.where(:view_type_id => 5).where(:object_id => blog_post.id).count %>
            <%if views.present?%>
              <%= views %>
            <%end%>
          </td>
          <% company = blog_post.company.slug %>
          <% user = blog_post.user.username %>
          <td><%= link_to 'Show', blog_post_blog_posts_path(company,user, blog_post), :target => "_blank" , class: "btn btn-primary btn-xs"%>
            <%= link_to 'Edit', edit_admin_company_blog_post_path(company, blog_post), class: "btn btn-primary btn-xs", class: "btn btn-primary btn-xs" %>
            <%= link_to 'Destroy',admin_company_blog_post_path(company ,blog_post) , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <br>
  <%if policy(BlogPost).new? && !is_super_admin? && current_user.company.present?%>
  <div class="form-group">
    <%= link_to 'New Blog Post', new_admin_company_blog_post_path(:company_id => current_user.company.slug), :class => "btn btn-primary" %>
    <%= link_to "Drafts", drafts_admin_company_blog_posts_path(:company_id => current_user.company.slug) , :class => "btn btn-primary"%>
  </div>
  <%elsif is_super_admin? && @company.present?%>
  <div class ="form-group">
    <%= link_to 'New Blog Post', new_admin_company_blog_post_path(:company_id => params[:company_id]), :class => "btn btn-primary" %>
  </div>
  <%end%>

app/views/admin/blog_posts/draft_posts.html.erb
<%= render 'admin/blog_posts/show_blog_posts' %>

app/views/admin/blog_posts/edit.html.slim
h5.valign.center Edit Post
.container
	#edit_blog_post
		== render 'form'

	

app/views/admin/blog_posts/index.html.erb
<%= render 'admin/blog_posts/show_blog_posts' %>

app/views/admin/blog_posts/new.html.erb
<div class="container-fluid">
	<h3>Add New Post</h3>
	<%= render '/admin/blog_posts/form' %>
</div>

app/views/admin/blog_posts/show.html.slim
= page_heading  @blog_post.title
= meta_keywords @blog_post.keywords
= meta_description @blog_post.description
.container-full
  p
    strong Title:
    = @blog_post.title
  p
    strong tags:
    = @blog_post.tags
  p
    #blog_post_body_content
      strong Body:
      = raw @blog_post.body
  p
    strong Post Category:
    - if @blog_post.post_categories.present?
                - @post_category = @blog_post.post_categories.map(&:name) 
                = raw(@post_category.map{|cat| cat}.join(', '))


.container.blog_wrap
  .row
      .col.m4.blog_featured_image_wrap
        .blog_featured_image.valign-wrapper
          = link_to (@blog_post.featured_image.url(:original)), :class=> "single_featured_image" , :rel => 'blog' , :data => {lightbox: image_url(@blog_post.id)} do
            -if @blog_post.featured_image.present?
              = image_tag(@blog_post.featured_image.url(:original), :class => "valign")
            -else
               = link_to image_tag("missing.png") , "/assets/missing.png" ,:rel => "blog", :data => {lightbox: image_url(@blog_post.id)}

.container
      -if policy(@blog_post).create?
        = link_to 'Edit |',  edit_admin_company_blog_post_path(@company, @blog_post), data: { turbolinks: false }
        = link_to ' Back |', admin_company_blog_posts_path(@company), data: { turbolinks: false }
        = link_to ' Destroy',  admin_company_blog_post_path(@company, @blog_post), method: :delete, data: { confirm: 'Are you sure?' }
      end


  '

app/views/admin/blog_posts/show_category_blog_posts.html.slim
== render 'admin/blog_posts/show_blog_posts'

app/views/admin/blog_posts/show_tags_blog_posts.html.slim
== render 'admin/blog_posts/show_blog_posts'